'use client';

/**
 * Home Page with React Flow Diagram
 * Generated by Roo
 */
import dynamic from "next/dynamic";

// Use dynamic import for the FlowDiagram component
const FlowDiagram = dynamic(
  () => import('@/components/FlowDiagram'),
  { ssr: false }
);

export default function Home() {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Next.js + Supabase + React Flow</h1>
      <div className="border rounded-lg overflow-hidden">
        <FlowDiagram />
      </div>
    </div>
  );
}
